# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0003_auto_20180114_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
