# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1)),
                ('count', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
