# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20180210_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='period_start',
            new_name='period',
        ),
    ]
