# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20180210_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='BleReport',
            fields=[
                ('report_type', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month')], max_length=1)),
                ('timezone', models.CharField(max_length=60)),
                ('period', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
