# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-08 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=60)),
                ('device_type', models.CharField(max_length=200)),
                ('seen_first', models.DateTimeField(auto_now=True)),
                ('seen_last', models.DateTimeField(auto_now=True)),
                ('seen_counter', models.PositiveIntegerField(default=1)),
                ('ignore', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('rssi', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ble.Device')),
            ],
        ),
    ]
