# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='seen_first',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
