# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0002_auto_20180114_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrecord',
            name='device',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ble.Device'),
        ),
    ]
