# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0004_auto_20180210_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scanrecord',
            options={'managed': True},
        ),
    ]
