# Generated by Django 2.2.13 on 2020-06-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0005_auto_20200609_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scanrecord',
            options={},
        ),
    ]
