# Generated by Django 2.2.13 on 2020-06-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0007_device_seen_within_geofence'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_manufacturer',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
