# Generated by Django 2.2.13 on 2020-06-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0008_device_device_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_manufacturer_string_raw',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
