# Generated by Django 2.2.13 on 2020-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ble', '0009_device_device_manufacturer_string_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_fingerprint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_manufacturer_string_raw',
            field=models.CharField(default='', max_length=60),
        ),
    ]
