#!/bin/bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

name=$(sed 's/\"//g' <<< $NAME)
if [[ ! $name =~ ^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$ ]]; then exit 0; fi

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")

case "$action" in
add)
    printf "discoverable off\npairable off\nexit\n" | bluetoothctl
    ;;
remove)
    printf "discoverable on\npairable on\nexit\n" | bluetoothctl
    ;;
esac
