# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20180114_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='range_end',
        ),
        migrations.AddField(
            model_name='report',
            name='data_source',
            field=models.CharField(default='ble', max_length=10),
        ),
    ]
