# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180210_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data_source',
            field=models.CharField(choices=[('B', 'BLE'), ('W', 'WiFi')], max_length=1),
        ),
    ]
