# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-09 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_auto_20180210_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blereport',
            options={'managed': True},
        ),
    ]
