FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run

ARG REDIS_VERSION=4.0.6
EXPOSE 6379
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get clean
RUN \
    wget -q -O /tmp/redis.tgz http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz && \
    tar xfz /tmp/redis.tgz -C /tmp && \
    cd /tmp/redis-${REDIS_VERSION} && \
    make && \
    make install && \
    cd && rm -rf /tmp/redis*
COPY redis.conf /etc

CMD /usr/local/bin/redis-server /etc/redis.conf
